"""add admin lock to driver wallet

Revision ID: 4918a012980d
Revises: 0026_vehicle_images_and_flexible_seat_count
Create Date: 2026-07-14 09:10:39.293679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4918a012980d'
down_revision = '0026_vehicle_images_and_flexible_seat_count'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    op.drop_table('items')
    op.drop_constraint(op.f('auth_tokens_token_key'), 'auth_tokens', type_='unique')
    op.drop_index(op.f('ix_auth_tokens_token'), table_name='auth_tokens')
    op.create_index(op.f('ix_auth_tokens_token'), 'auth_tokens', ['token'], unique=True)
    op.drop_constraint(op.f('booking_payment_instructions_booking_id_key'), 'booking_payment_instructions', type_='unique')
    op.drop_index(op.f('ix_bookings_settlement_summary_date'), table_name='bookings')
    op.drop_constraint(op.f('driver_wallet_entries_booking_id_key'), 'driver_wallet_entries', type_='unique')
    op.drop_index(op.f('ix_driver_wallet_entries_booking_id'), table_name='driver_wallet_entries')
    op.create_index(op.f('ix_driver_wallet_entries_booking_id'), 'driver_wallet_entries', ['booking_id'], unique=True)
    op.add_column('driver_wallets', sa.Column('admin_locked', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('driver_wallets', sa.Column('admin_locked_reason', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('payments_transaction_id_key'), 'payments', type_='unique')
    op.drop_index(op.f('ix_payments_transaction_id'), table_name='payments')
    op.create_index(op.f('ix_payments_transaction_id'), 'payments', ['transaction_id'], unique=True)
    op.drop_constraint(op.f('trusted_devices_device_id_hash_key'), 'trusted_devices', type_='unique')
    op.drop_index(op.f('ix_trusted_devices_device_id_hash'), table_name='trusted_devices')
    op.create_index(op.f('ix_trusted_devices_device_id_hash'), 'trusted_devices', ['device_id_hash'], unique=True)
    op.drop_constraint(op.f('users_phone_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.drop_constraint(op.f('vehicles_plate_number_key'), 'vehicles', type_='unique')
    op.drop_index(op.f('ix_vehicles_plate_number'), table_name='vehicles')
    op.create_index(op.f('ix_vehicles_plate_number'), 'vehicles', ['plate_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_plate_number'), table_name='vehicles')
    op.create_index(op.f('ix_vehicles_plate_number'), 'vehicles', ['plate_number'], unique=False)
    op.create_unique_constraint(op.f('vehicles_plate_number_key'), 'vehicles', ['plate_number'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_unique_constraint(op.f('users_phone_key'), 'users', ['phone'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_trusted_devices_device_id_hash'), table_name='trusted_devices')
    op.create_index(op.f('ix_trusted_devices_device_id_hash'), 'trusted_devices', ['device_id_hash'], unique=False)
    op.create_unique_constraint(op.f('trusted_devices_device_id_hash_key'), 'trusted_devices', ['device_id_hash'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_payments_transaction_id'), table_name='payments')
    op.create_index(op.f('ix_payments_transaction_id'), 'payments', ['transaction_id'], unique=False)
    op.create_unique_constraint(op.f('payments_transaction_id_key'), 'payments', ['transaction_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('driver_wallets', 'admin_locked_reason')
    op.drop_column('driver_wallets', 'admin_locked')
    op.drop_index(op.f('ix_driver_wallet_entries_booking_id'), table_name='driver_wallet_entries')
    op.create_index(op.f('ix_driver_wallet_entries_booking_id'), 'driver_wallet_entries', ['booking_id'], unique=False)
    op.create_unique_constraint(op.f('driver_wallet_entries_booking_id_key'), 'driver_wallet_entries', ['booking_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_bookings_settlement_summary_date'), 'bookings', ['settlement_summary_date'], unique=False)
    op.create_unique_constraint(op.f('booking_payment_instructions_booking_id_key'), 'booking_payment_instructions', ['booking_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_auth_tokens_token'), table_name='auth_tokens')
    op.create_index(op.f('ix_auth_tokens_token'), 'auth_tokens', ['token'], unique=False)
    op.create_unique_constraint(op.f('auth_tokens_token_key'), 'auth_tokens', ['token'], postgresql_nulls_not_distinct=False)
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('items_pkey'))
    )
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('categories_pkey'))
    )
    # ### end Alembic commands ###
